### ISSUE TITLE
扫码登陆后 主页获取数据失败,稍后再试

### ISSUE THREAD

**Issue by geekscloud** [Richasy/Bili.Mac.MenuBar#4]
系统 13.0 Beta版(22A5342f)

**Comment by Richasy** [comment]
是开了网络代理么？

**Comment by geekscloud** [comment]
是的，使用了loon 作为代理，不兼容代理吗

**Comment by Richasy** [comment]
网络代理的话有点特殊，可能是流量劫持导致应用无法访问网络，关闭代理或者设置为系统网络代理应该可行，但这一部分内容已经超出应用本身，目前不做处理
